# Generated by Django 5.1.5 on 2025-01-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cashless', 'Cashless')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], max_length=50),
        ),
    ]
