# Generated by Django 5.1.5 on 2025-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_order_status_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
